//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServices.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string NameNews { get; set; }
        public string News1 { get; set; }
        public string Image { get; set; }
    }
}
