//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServices.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportsID { get; set; }
        public string ReportsName { get; set; }
        public Nullable<System.DateTime> ReportsData { get; set; }
        public Nullable<int> NumberOfOrders { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
